service: serverless-w-rds

frameworkVersion: ">=2.0.0"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  lambdaHashingVersion: '20201221'
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
  iamRoleStatements:
    - Effect: Allow
      Action: '*'
      Resource: "*"

functions:
  index:
    handler: src/index.handler
    events:
      - http:
          path: test
          method: get
          cors: true
